/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kubility_demo_MP3Recorder */

#ifndef _Included_MP3Recorder
#define _Included_MP3Recorder
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_foretree_media_MP3Recorder_init
        (JNIEnv *, jclass, jint, jint, jint, jint, jint);

JNIEXPORT jint JNICALL Java_com_foretree_media_MP3Recorder_encode
        (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

JNIEXPORT jint JNICALL Java_com_foretree_media_MP3Recorder_flush
        (JNIEnv *, jclass, jbyteArray);

JNIEXPORT void JNICALL Java_com_foretree_media_MP3Recorder_close
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif